// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DbContextEF))]
    [Migration("20240215141917_EditNameBankSafe")]
    partial class EditNameBankSafe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entity.BankAccount", b =>
                {
                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AccountNumber");

                    b.HasIndex("UserName");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("Domain.Entity.BankSafe", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("SharePrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Name");

                    b.ToTable("BankSafes");
                });

            modelBuilder.Entity("Domain.Entity.BankSafeDocument", b =>
                {
                    b.Property<Guid>("CodeDocuments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DepositPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DueDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameBankSafe")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RegistrationDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Situation")
                        .HasColumnType("int");

                    b.Property<decimal>("WithdrawalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodeDocuments");

                    b.HasIndex("AccountNumber");

                    b.HasIndex("NameBankSafe");

                    b.ToTable("BankSafeDocument");
                });

            modelBuilder.Entity("Domain.Entity.BankSafeTransactions", b =>
                {
                    b.Property<Guid>("CodeTransactions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DepositPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NameBankSafe")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("WithdrawalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodeTransactions");

                    b.HasIndex("AccountNumber");

                    b.HasIndex("NameBankSafe");

                    b.ToTable("BankSafeTransactions");
                });

            modelBuilder.Entity("Domain.Entity.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalIDNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roll")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entity.UserSharePrice", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NameBankSafe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NumberOfShares")
                        .HasColumnType("int");

                    b.HasKey("UserName", "NameBankSafe");

                    b.HasIndex("NameBankSafe");

                    b.ToTable("UserSharePrices");
                });

            modelBuilder.Entity("Domain.Entity.BankAccount", b =>
                {
                    b.HasOne("Domain.Entity.User", "User")
                        .WithMany("BankAccounts")
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.BankSafeDocument", b =>
                {
                    b.HasOne("Domain.Entity.BankAccount", "BankAccount")
                        .WithMany("BankSafeDocuments")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.BankSafe", "BankSafe")
                        .WithMany("BankSafeDocuments")
                        .HasForeignKey("NameBankSafe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");

                    b.Navigation("BankSafe");
                });

            modelBuilder.Entity("Domain.Entity.BankSafeTransactions", b =>
                {
                    b.HasOne("Domain.Entity.BankAccount", "BankAccount")
                        .WithMany("BankSafeTransactions")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.BankSafe", "BankSafe")
                        .WithMany("BankSafeTransactions")
                        .HasForeignKey("NameBankSafe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");

                    b.Navigation("BankSafe");
                });

            modelBuilder.Entity("Domain.Entity.UserSharePrice", b =>
                {
                    b.HasOne("Domain.Entity.BankSafe", "BankSafe")
                        .WithMany("UserSharePrices")
                        .HasForeignKey("NameBankSafe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.User", "User")
                        .WithMany("UserSharePrices")
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankSafe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.BankAccount", b =>
                {
                    b.Navigation("BankSafeDocuments");

                    b.Navigation("BankSafeTransactions");
                });

            modelBuilder.Entity("Domain.Entity.BankSafe", b =>
                {
                    b.Navigation("BankSafeDocuments");

                    b.Navigation("BankSafeTransactions");

                    b.Navigation("UserSharePrices");
                });

            modelBuilder.Entity("Domain.Entity.User", b =>
                {
                    b.Navigation("BankAccounts");

                    b.Navigation("UserSharePrices");
                });
#pragma warning restore 612, 618
        }
    }
}
